/*
 jQuery v2.1.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(m,z,r){m instanceof String&&(m=String(m));for(var F=m.length,y=0;y<F;y++){var Q=m[y];if(z.call(r,Q,y,m))return{i:y,v:Q}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(m,z,r){m!=Array.prototype&&m!=Object.prototype&&(m[z]=r.value)};
$jscomp.getGlobal=function(m){return"undefined"!=typeof window&&window===m?m:"undefined"!=typeof global&&null!=global?global:m};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(m,z,r,F){if(z){r=$jscomp.global;m=m.split(".");for(F=0;F<m.length-1;F++){var y=m[F];y in r||(r[y]={});r=r[y]}m=m[m.length-1];F=r[m];z=z(F);z!=F&&null!=z&&$jscomp.defineProperty(r,m,{configurable:!0,writable:!0,value:z})}};
$jscomp.polyfill("Array.prototype.find",function(m){return m?m:function(m,r){return $jscomp.findInternal(this,m,r).v}},"es6","es3");
!function(m,z){"object"==typeof module&&"object"==typeof module.exports?module.exports=m.document?z(m,!0):function(m){if(!m.document)throw Error("jQuery requires a window with a document");return z(m)}:z(m)}("undefined"!=typeof window?window:this,function(m,z){function r(a){var b=a.length,d=c.type(a);return"function"===d||c.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===d||0===b||"number"==typeof b&&0<b&&b-1 in a}function F(a,b,d){if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,
a)!==d});if(b.nodeType)return c.grep(a,function(a){return a===b!==d});if("string"==typeof b){if(Hb.test(b))return c.filter(b,a,d);b=c.filter(b,a)}return c.grep(a,function(a){return 0<=va.call(b,a)!==d})}function y(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function Q(a){var b=Ua[a]={};return c.each(a.match(T)||[],function(a,c){b[c]=!0}),b}function wa(){u.removeEventListener("DOMContentLoaded",wa,!1);m.removeEventListener("load",wa,!1);c.ready()}function ea(){Object.defineProperty(this.cache={},
0,{get:function(){return{}}});this.expando=c.expando+Math.random()}function xa(a,b,d){var f;if(void 0===d&&1===a.nodeType)if(f="data-"+b.replace(Ib,"-$1").toLowerCase(),d=a.getAttribute(f),"string"==typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:Jb.test(d)?c.parseJSON(d):d}catch(e){}B.set(a,b,d)}else d=void 0;return d}function M(){return!0}function U(){return!1}function Va(){try{return u.activeElement}catch(a){}}function Wa(a,b){return c.nodeName(a,"table")&&c.nodeName(11!==
b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function Kb(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function Lb(a){var b=Mb.exec(a.type);return b?a.type=b[1]:a.removeAttribute("type"),a}function Ha(a,b){for(var d=0,c=a.length;c>d;d++)w.set(a[d],"globalEval",!b||w.get(b[d],"globalEval"))}function Xa(a,b){var d,f,e,g,h,k;if(1===b.nodeType){if(w.hasData(a)&&(d=w.access(a),f=w.set(b,d),k=d.events))for(e in delete f.handle,
f.events={},k)for(d=0,f=k[e].length;f>d;d++)c.event.add(b,e,k[e][d]);B.hasData(a)&&(g=B.access(a),h=c.extend({},g),B.set(b,h))}}function C(a,b){var d=a.getElementsByTagName?a.getElementsByTagName(b||"*"):a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&c.nodeName(a,b)?c.merge([a],d):d}function Ya(a,b){var d;a=c(b.createElement(a)).appendTo(b.body);b=m.getDefaultComputedStyle&&(d=m.getDefaultComputedStyle(a[0]))?d.display:c.css(a[0],"display");return a.detach(),b}function Ia(a){var b=
u,d=Za[a];return d||(d=Ya(a,b),"none"!==d&&d||(ha=(ha||c("<iframe frameborder='0' width='0' height='0'/>")).appendTo(b.documentElement),b=ha[0].contentDocument,b.write(),b.close(),d=Ya(a,b),ha.detach()),Za[a]=d),d}function qa(a,b,d){var f,e,g,h,k=a.style;return d=d||ya(a),d&&(h=d.getPropertyValue(b)||d[b]),d&&(""!==h||c.contains(a.ownerDocument,a)||(h=c.style(a,b)),Ja.test(h)&&$a.test(b)&&(f=k.width,e=k.minWidth,g=k.maxWidth,k.minWidth=k.maxWidth=k.width=h,h=d.width,k.width=f,k.minWidth=e,k.maxWidth=
g)),void 0!==h?h+"":h}function ab(a,b){return{get:function(){return a()?void delete this.get:(this.get=b).apply(this,arguments)}}}function bb(a,b){if(b in a)return b;for(var d=b[0].toUpperCase()+b.slice(1),c=b,e=cb.length;e--;)if(b=cb[e]+d,b in a)return b;return c}function db(a,b,d){return(a=Nb.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function eb(a,b,d,f,e){b=d===(f?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+Y[b],!0,e)),f?("content"===d&&(g-=c.css(a,
"padding"+Y[b],!0,e)),"margin"!==d&&(g-=c.css(a,"border"+Y[b]+"Width",!0,e))):(g+=c.css(a,"padding"+Y[b],!0,e),"padding"!==d&&(g+=c.css(a,"border"+Y[b]+"Width",!0,e)));return g}function fb(a,b,d){var f=!0,e="width"===b?a.offsetWidth:a.offsetHeight,g=ya(a),h="border-box"===c.css(a,"boxSizing",!1,g);if(0>=e||null==e){if(e=qa(a,b,g),(0>e||null==e)&&(e=a.style[b]),Ja.test(e))return e;f=h&&(x.boxSizingReliable()||e===a.style[b]);e=parseFloat(e)||0}return e+eb(a,b,d||(h?"border":"content"),f,g)+"px"}function gb(a,
b){for(var d,f,e,g=[],h=0,k=a.length;k>h;h++)f=a[h],f.style&&(g[h]=w.get(f,"olddisplay"),d=f.style.display,b?(g[h]||"none"!==d||(f.style.display=""),""===f.style.display&&Z(f)&&(g[h]=w.access(f,"olddisplay",Ia(f.nodeName)))):(e=Z(f),"none"===d&&e||w.set(f,"olddisplay",e?d:c.css(f,"display"))));for(h=0;k>h;h++)f=a[h],f.style&&(b&&"none"!==f.style.display&&""!==f.style.display||(f.style.display=b?g[h]||"":"none"));return a}function H(a,b,d,c,e){return new H.prototype.init(a,b,d,c,e)}function hb(){return setTimeout(function(){ia=
void 0}),ia=c.now()}function za(a,b){var d=0,c={height:a};for(b=b?1:0;4>d;d+=2-b){var e=Y[d];c["margin"+e]=c["padding"+e]=a}return b&&(c.opacity=c.width=a),c}function ib(a,b,d){for(var c,e=(ra[b]||[]).concat(ra["*"]),g=0,h=e.length;h>g;g++)if(c=e[g].call(d,b,a))return c}function Ob(a,b){var d,f,e,g,h;for(d in a)if(f=c.camelCase(d),e=b[f],g=a[d],c.isArray(g)&&(e=g[1],g=a[d]=g[0]),d!==f&&(a[f]=g,delete a[d]),h=c.cssHooks[f],h&&"expand"in h)for(d in g=h.expand(g),delete a[f],g)d in a||(a[d]=g[d],b[d]=
e);else b[f]=e}function jb(a,b,d){var f,e=0,g=ja.length,h=c.Deferred().always(function(){delete k.elem}),k=function(){if(f)return!1;var b=ia||hb();b=Math.max(0,l.startTime+l.duration-b);for(var d=1-(b/l.duration||0),c=0,e=l.tweens.length;e>c;c++)l.tweens[c].run(d);return h.notifyWith(a,[l,d,b]),1>d&&e?b:(h.resolveWith(a,[l]),!1)},l=h.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:ia||hb(),duration:d.duration,tweens:[],createTween:function(b,
d){b=c.Tween(a,l.opts,b,d,l.opts.specialEasing[b]||l.opts.easing);return l.tweens.push(b),b},stop:function(b){var d=0,c=b?l.tweens.length:0;if(f)return this;for(f=!0;c>d;d++)l.tweens[d].run(1);return b?h.resolveWith(a,[l,b]):h.rejectWith(a,[l,b]),this}});d=l.props;for(Ob(d,l.opts.specialEasing);g>e;e++)if(b=ja[e].call(l,a,d,l.opts))return b;return c.map(d,ib,l),c.isFunction(l.opts.start)&&l.opts.start.call(a,l),c.fx.timer(c.extend(k,{elem:a,anim:l,queue:l.opts.queue})),l.progress(l.opts.progress).done(l.opts.done,
l.opts.complete).fail(l.opts.fail).always(l.opts.always)}function kb(a){return function(b,d){"string"!=typeof b&&(d=b,b="*");var f=0,e=b.toLowerCase().match(T)||[];if(c.isFunction(d))for(;b=e[f++];)"+"===b[0]?(b=b.slice(1)||"*",(a[b]=a[b]||[]).unshift(d)):(a[b]=a[b]||[]).push(d)}}function lb(a,b,d,f){function e(k){var l;return g[k]=!0,c.each(a[k]||[],function(a,c){a=c(b,d,f);return"string"!=typeof a||h||g[a]?h?!(l=a):void 0:(b.dataTypes.unshift(a),e(a),!1)}),l}var g={},h=a===Ka;return e(b.dataTypes[0])||
!g["*"]&&e("*")}function La(a,b){var d,f,e=c.ajaxSettings.flatOptions||{};for(d in b)void 0!==b[d]&&((e[d]?a:f||(f={}))[d]=b[d]);return f&&c.extend(!0,a,f),a}function Ma(a,b,d,f){var e;if(c.isArray(b))c.each(b,function(b,c){d||Pb.test(a)?f(a,c):Ma(a+"["+("object"==typeof c?b:"")+"]",c,d,f)});else if(d||"object"!==c.type(b))f(a,b);else for(e in b)Ma(a+"["+e+"]",b[e],d,f)}function mb(a){return c.isWindow(a)?a:9===a.nodeType&&a.defaultView}var ka=[],V=ka.slice,nb=ka.concat,Na=ka.push,va=ka.indexOf,fa=
{},Qb=fa.toString,Oa=fa.hasOwnProperty,x={},u=m.document,c=function(a,b){return new c.fn.init(a,b)},Rb=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,Sb=/^-ms-/,Tb=/-([\da-z])/gi,Ub=function(a,b){return b.toUpperCase()};c.fn=c.prototype={jquery:"2.1.1",constructor:c,selector:"",length:0,toArray:function(){return V.call(this)},get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:V.call(this)},pushStack:function(a){a=c.merge(this.constructor(),a);return a.prevObject=this,a.context=this.context,a},each:function(a,
b){return c.each(this,a,b)},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},slice:function(){return this.pushStack(V.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&b>a?[this[a]]:[])},end:function(){return this.prevObject||this.constructor(null)},push:Na,sort:ka.sort,splice:ka.splice};c.extend=c.fn.extend=function(){var a,b,d,f,e=arguments[0]||
{},g=1,h=arguments.length,k=!1;"boolean"==typeof e&&(k=e,e=arguments[g]||{},g++);"object"==typeof e||c.isFunction(e)||(e={});for(g===h&&(e=this,g--);h>g;g++)if(null!=(a=arguments[g]))for(b in a){var l=e[b];var p=a[b];e!==p&&(k&&p&&(c.isPlainObject(p)||(d=c.isArray(p)))?(d?(d=!1,f=l&&c.isArray(l)?l:[]):f=l&&c.isPlainObject(l)?l:{},e[b]=c.extend(k,f,p)):void 0!==p&&(e[b]=p))}return e};c.extend({expando:"jQuery"+("2.1.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},
noop:function(){},isFunction:function(a){return"function"===c.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){return!c.isArray(a)&&0<=a-parseFloat(a)},isPlainObject:function(a){return"object"!==c.type(a)||a.nodeType||c.isWindow(a)?!1:a.constructor&&!Oa.call(a.constructor.prototype,"isPrototypeOf")?!1:!0},isEmptyObject:function(a){for(var b in a)return!1;return!0},type:function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?fa[Qb.call(a)]||
"object":typeof a},globalEval:function(a){var b,d=eval;(a=c.trim(a))&&(1===a.indexOf("use strict")?(b=u.createElement("script"),b.text=a,u.head.appendChild(b).parentNode.removeChild(b)):d(a))},camelCase:function(a){return a.replace(Sb,"ms-").replace(Tb,Ub)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,d){var c,e=0,g=a.length,h=r(a);if(d)if(h)for(;g>e&&(c=b.apply(a[e],d),!1!==c);e++);else for(e in a){if(c=b.apply(a[e],d),!1===c)break}else if(h)for(;g>
e&&(c=b.call(a[e],e,a[e]),!1!==c);e++);else for(e in a)if(c=b.call(a[e],e,a[e]),!1===c)break;return a},trim:function(a){return null==a?"":(a+"").replace(Rb,"")},makeArray:function(a,b){b=b||[];return null!=a&&(r(Object(a))?c.merge(b,"string"==typeof a?[a]:a):Na.call(b,a)),b},inArray:function(a,b,d){return null==b?-1:va.call(b,a,d)},merge:function(a,b){for(var d=+b.length,c=0,e=a.length;d>c;c++)a[e++]=b[c];return a.length=e,a},grep:function(a,b,d){for(var c=[],e=0,g=a.length,h=!d;g>e;e++)d=!b(a[e],
e),d!==h&&c.push(a[e]);return c},map:function(a,b,d){var c=0,e=a.length,g=[];if(r(a))for(;e>c;c++){var h=b(a[c],c,d);null!=h&&g.push(h)}else for(c in a)h=b(a[c],c,d),null!=h&&g.push(h);return nb.apply([],g)},guid:1,proxy:function(a,b){var d,f,e;return"string"==typeof b&&(d=a[b],b=a,a=d),c.isFunction(a)?(f=V.call(arguments,2),e=function(){return a.apply(b||this,f.concat(V.call(arguments)))},e.guid=a.guid=a.guid||c.guid++,e):void 0},now:Date.now,support:x});c.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),
function(a,b){fa["[object "+b+"]"]=b.toLowerCase()});var oa=function(a){function b(a,b,c,d){var f,e,g,t,h;if((b?b.ownerDocument||b:W)!==O&&sa(b),b=b||O,c=c||[],!a||"string"!=typeof a)return c;if(1!==(t=b.nodeType)&&9!==t)return[];if(ba&&!d){if(f=va.exec(a))if(g=f[1])if(9===t){if(e=b.getElementById(g),!e||!e.parentNode)return c;if(e.id===g)return c.push(e),c}else{if(b.ownerDocument&&(e=b.ownerDocument.getElementById(g))&&C(b,e)&&e.id===g)return c.push(e),c}else{if(f[2])return M.apply(c,b.getElementsByTagName(a)),
c;if((g=f[3])&&K.getElementsByClassName&&b.getElementsByClassName)return M.apply(c,b.getElementsByClassName(g)),c}if(K.qsa&&(!S||!S.test(a))){if(e=f=D,g=b,h=9===t&&a,1===t&&"object"!==b.nodeName.toLowerCase()){t=fa(a);(f=b.getAttribute("id"))?e=f.replace(ya,"\\$&"):b.setAttribute("id",e);e="[id='"+e+"'] ";for(g=t.length;g--;)t[g]=e+m(t[g]);g=ha.test(a)&&n(b.parentNode)||b;h=t.join(",")}if(h)try{return M.apply(c,g.querySelectorAll(h)),c}catch(yc){}finally{f||b.removeAttribute("id")}}}return F(a.replace(U,
"$1"),b,c,d)}function d(){function a(c,d){return b.push(c+" ")>E.cacheLength&&delete a[b.shift()],a[c+" "]=d}var b=[];return a}function c(a){return a[D]=!0,a}function e(a){var b=O.createElement("div");try{return!!a(b)}catch(aa){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){var c=a.split("|");for(a=a.length;a--;)E.attrHandle[c[a]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(d)return d;
if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function p(a){return c(function(b){return b=+b,c(function(c,d){for(var f,e=a([],c.length,b),g=e.length;g--;)c[f=e[g]]&&(c[f]=!(d[f]=c[f]))})})}function n(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function q(){}function m(a){for(var b=
0,c=a.length,d="";c>b;b++)d+=a[b].value;return d}function w(a,b,c){var d=b.dir,f=c&&"parentNode"===d,e=Vb++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||f)return a(b,c,e)}:function(b,c,g){var t,h,k=[ca,e];if(g)for(;b=b[d];){if((1===b.nodeType||f)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||f){if(h=b[D]||(b[D]={}),(t=h[d])&&t[0]===ca&&t[1]===e)return k[2]=t[2];if(h[d]=k,k[2]=a(b,c,g))return!0}}}function v(a){return 1<a.length?function(b,c,d){for(var f=a.length;f--;)if(!a[f](b,
c,d))return!1;return!0}:a[0]}function u(a,b,c,d,f){for(var e,g=[],h=0,t=a.length,k=null!=b;t>h;h++)(e=a[h])&&(!c||c(e,d,f))&&(g.push(e),k&&b.push(h));return g}function r(a,d,f,e,g,h){return e&&!e[D]&&(e=r(e)),g&&!g[D]&&(g=r(g,h)),c(function(c,h,t,k){var l,R=[],aa=[],n=h.length,N;if(!(N=c)){N=d||"*";for(var J=t.nodeType?[t]:t,Ba=[],p=0,q=J.length;q>p;p++)b(N,J[p],Ba);N=Ba}N=!a||!c&&d?N:u(N,R,a,t,k);J=f?g||(c?a:n||e)?[]:h:N;if(f&&f(N,J,t,k),e){var m=u(J,aa);e(m,[],t,k);for(t=m.length;t--;)(l=m[t])&&
(J[aa[t]]=!(N[aa[t]]=l))}if(c){if(g||a){if(g){m=[];for(t=J.length;t--;)(l=J[t])&&m.push(N[t]=l);g(null,J=[],m,k)}for(t=J.length;t--;)(l=J[t])&&-1<(m=g?G.call(c,l):R[t])&&(c[m]=!(h[m]=l))}}else J=u(J===h?J.splice(n,J.length):J),g?g(null,h,J,k):M.apply(h,J)})}function x(a){var b,c,d=a.length,f=E.relative[a[0].type];var e=f||E.relative[" "];for(var g=f?1:0,h=w(function(a){return a===b},e,!0),t=w(function(a){return-1<G.call(b,a)},e,!0),k=[function(a,c,d){return!f&&(d||c!==P)||((b=c).nodeType?h(a,c,d):
t(a,c,d))}];d>g;g++)if(e=E.relative[a[g].type])k=[w(v(k),e)];else{if(e=E.filter[a[g].type].apply(null,a[g].matches),e[D]){for(c=++g;d>c&&!E.relative[a[c].type];c++);return r(1<g&&v(k),1<g&&m(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(U,"$1"),e,c>g&&x(a.slice(g,c)),d>c&&x(a=a.slice(c)),d>c&&m(a))}k.push(e)}return v(k)}function z(a,d){var f=0<d.length,e=0<a.length,g=function(c,g,h,t,k){var l,n,R,aa=0,N="0",J=c&&[],p=[],q=P,m=c||e&&E.find.TAG("*",k),Ba=ca+=null==q?1:Math.random()||
.1,w=m.length;for(k&&(P=g!==O&&g);N!==w&&null!=(l=m[N]);N++){if(e&&l){for(n=0;R=a[n++];)if(R(l,g,h)){t.push(l);break}k&&(ca=Ba)}f&&((l=!R&&l)&&aa--,c&&J.push(l))}if(aa+=N,f&&N!==aa){for(n=0;R=d[n++];)R(J,p,g,h);if(c){if(0<aa)for(;N--;)J[N]||p[N]||(p[N]=wa.call(t));p=u(p)}M.apply(t,p);k&&!c&&0<p.length&&1<aa+d.length&&b.uniqueSort(t)}return k&&(ca=Ba,P=q),J};return f?c(g):g}var B,A,F,P,I,Aa,O,y,ba,S,ta,Ca,C,D="sizzle"+-new Date,W=a.document,ca=0,Vb=0,H=d(),Q=d(),ob=d(),L=function(a,b){return a===b&&
(Aa=!0),0},T={}.hasOwnProperty,la=[],wa=la.pop,ea=la.push,M=la.push,V=la.slice,G=la.indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(this[b]===a)return b;return-1},Y="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),da="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|("+Y+"))|)[\\x20\\t\\r\\n\\f]*\\]",xa=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|"+
da+")*)|.*)\\)|)",U=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,ia=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ka=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,oa=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,pa=new RegExp(xa),qa=new RegExp("^"+Y+"$"),Z={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:new RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:new RegExp("^"+da),PSEUDO:new RegExp("^"+xa),CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,
bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},ra=/^(?:input|select|textarea|button)$/i,ua=/^h\d$/i,X=/^[^{]+\{\s*\[native \w/,va=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ha=/[+~]/,ya=/'|\\/g,ma=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,na=function(a,b,c){a="0x"+b-65536;
return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,1023&a|56320)};try{M.apply(la=V.call(W.childNodes),W.childNodes),la[W.childNodes.length].nodeType}catch(t){M={apply:la.length?function(a,b){ea.apply(a,V.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var K=b.support={};var za=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};var sa=b.setDocument=function(a){var b,c=a?a.ownerDocument||a:W;a=c.defaultView;
return c!==O&&9===c.nodeType&&c.documentElement?(O=c,y=c.documentElement,ba=!za(c),a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){sa()},!1):a.attachEvent&&a.attachEvent("onunload",function(){sa()})),K.attributes=e(function(a){return a.className="i",!a.getAttribute("className")}),K.getElementsByTagName=e(function(a){return a.appendChild(c.createComment("")),!a.getElementsByTagName("*").length}),K.getElementsByClassName=X.test(c.getElementsByClassName)&&e(function(a){return a.innerHTML=
"<div class='a'></div><div class='a i'></div>",a.firstChild.className="i",2===a.getElementsByClassName("i").length}),K.getById=e(function(a){return y.appendChild(a).id=D,!c.getElementsByName||!c.getElementsByName(D).length}),K.getById?(E.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&ba)return(a=b.getElementById(a))&&a.parentNode?[a]:[]},E.filter.ID=function(a){var b=a.replace(ma,na);return function(a){return a.getAttribute("id")===b}}):(delete E.find.ID,E.filter.ID=function(a){var b=
a.replace(ma,na);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}}),E.find.TAG=K.getElementsByTagName?function(a,b){return"undefined"!==typeof b.getElementsByTagName?b.getElementsByTagName(a):void 0}:function(a,b){var c=[],d=0;b=b.getElementsByTagName(a);if("*"===a){for(;a=b[d++];)1===a.nodeType&&c.push(a);return c}return b},E.find.CLASS=K.getElementsByClassName&&function(a,b){return"undefined"!==typeof b.getElementsByClassName&&ba?b.getElementsByClassName(a):
void 0},ta=[],S=[],(K.qsa=X.test(c.querySelectorAll))&&(e(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&S.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||S.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||S.push(":checked")}),
e(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&S.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||S.push(":enabled",":disabled");a.querySelectorAll("*,:x");S.push(",.*:")})),(K.matchesSelector=X.test(Ca=y.matches||y.webkitMatchesSelector||y.mozMatchesSelector||y.oMatchesSelector||y.msMatchesSelector))&&e(function(a){K.disconnectedMatch=Ca.call(a,"div");Ca.call(a,
"[s!='']:x");ta.push("!=",xa)}),S=S.length&&new RegExp(S.join("|")),ta=ta.length&&new RegExp(ta.join("|")),b=X.test(y.compareDocumentPosition),C=b||X.test(y.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a;b=b&&b.parentNode;return a===b||!(!b||1!==b.nodeType||!(c.contains?c.contains(b):a.compareDocumentPosition&&16&a.compareDocumentPosition(b)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},L=b?function(a,b){if(a===b)return Aa=!0,0;var d=!a.compareDocumentPosition-
!b.compareDocumentPosition;return d?d:(d=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):1,1&d||!K.sortDetached&&b.compareDocumentPosition(a)===d?a===c||a.ownerDocument===W&&C(W,a)?-1:b===c||b.ownerDocument===W&&C(W,b)?1:I?G.call(I,a)-G.call(I,b):0:4&d?-1:1)}:function(a,b){if(a===b)return Aa=!0,0;var d=0,f=a.parentNode,e=b.parentNode,g=[a],t=[b];if(!f||!e)return a===c?-1:b===c?1:f?-1:e?1:I?G.call(I,a)-G.call(I,b):0;if(f===e)return h(a,b);for(;a=a.parentNode;)g.unshift(a);
for(a=b;a=a.parentNode;)t.unshift(a);for(;g[d]===t[d];)d++;return d?h(g[d],t[d]):g[d]===W?-1:t[d]===W?1:0},c):O};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){if((a.ownerDocument||a)!==O&&sa(a),c=c.replace(oa,"='$1']"),!(!K.matchesSelector||!ba||ta&&ta.test(c)||S&&S.test(c)))try{var d=Ca.call(a,c);if(d||K.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(N){}return 0<b(c,O,null,[a]).length};b.contains=function(a,b){return(a.ownerDocument||a)!==
O&&sa(a),C(a,b)};b.attr=function(a,b){(a.ownerDocument||a)!==O&&sa(a);var c=E.attrHandle[b.toLowerCase()];c=c&&T.call(E.attrHandle,b.toLowerCase())?c(a,b,!ba):void 0;return void 0!==c?c:K.attributes||!ba?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,f=0;if(Aa=!K.detectDuplicates,I=!K.sortStable&&a.slice(0),a.sort(L),Aa){for(;b=a[f++];)b===a[f]&&(d=c.push(f));
for(;d--;)a.splice(c[d],1)}return I=null,a};var ja=b.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=ja(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=ja(b);return c};var E=b.selectors={cacheLength:50,createPseudo:c,match:Z,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},
preFilter:{ATTR:function(a){return a[1]=a[1].replace(ma,na),a[3]=(a[3]||a[4]||a[5]||"").replace(ma,na),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=a[1].toLowerCase(),"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]),a},PSEUDO:function(a){var b,c=!a[6]&&a[2];return Z.CHILD.test(a[0])?null:(a[3]?a[2]=a[4]||a[5]||"":c&&pa.test(c)&&(b=fa(c,!0))&&(b=c.indexOf(")",
c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b)),a.slice(0,3))}},filter:{TAG:function(a){var b=a.replace(ma,na).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=H[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),H(a,function(a){return b.test("string"==typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,
c,d){return function(f){f=b.attr(f,a);return null==f?"!="===c:c?(f+="","="===c?f===d:"!="===c?f!==d:"^="===c?d&&0===f.indexOf(d):"*="===c?d&&-1<f.indexOf(d):"$="===c?d&&f.slice(-d.length)===d:"~="===c?-1<(" "+f+" ").indexOf(d):"|="===c?f===d||f.slice(0,d.length+1)===d+"-":!1):!0}},CHILD:function(a,b,c,d,f){var e="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===f?function(a){return!!a.parentNode}:function(b,c,k){var l;c=e!==g?"nextSibling":"previousSibling";var t=b.parentNode,
n=h&&b.nodeName.toLowerCase();k=!k&&!h;if(t){if(e){for(;c;){for(l=b;l=l[c];)if(h?l.nodeName.toLowerCase()===n:1===l.nodeType)return!1;var p=c="only"===a&&!p&&"nextSibling"}return!0}if(p=[g?t.firstChild:t.lastChild],g&&k){k=t[D]||(t[D]={});var q=k[a]||[];var R=q[0]===ca&&q[1];var m=q[0]===ca&&q[2];for(l=R&&t.childNodes[R];l=++R&&l&&l[c]||(m=R=0)||p.pop();)if(1===l.nodeType&&++m&&l===b){k[a]=[ca,R,m];break}}else if(k&&(q=(b[D]||(b[D]={}))[a])&&q[0]===ca)m=q[1];else for(;(l=++R&&l&&l[c]||(m=R=0)||p.pop())&&
((h?l.nodeName.toLowerCase()!==n:1!==l.nodeType)||!++m||(k&&((l[D]||(l[D]={}))[a]=[ca,m]),l!==b)););return m-=f,m===d||0===m%d&&0<=m/d}}},PSEUDO:function(a,d){var f,e=E.pseudos[a]||E.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return e[D]?e(d):1<e.length?(f=[a,a,"",d],E.setFilters.hasOwnProperty(a.toLowerCase())?c(function(a,b){for(var c,f=e(a,d),g=f.length;g--;)c=G.call(a,f[g]),a[c]=!(b[c]=f[g])}):function(a){return e(a,0,f)}):e}},pseudos:{not:c(function(a){var b=[],d=[],f=A(a.replace(U,
"$1"));return f[D]?c(function(a,b,c,d){var e;c=f(a,null,d,[]);for(d=a.length;d--;)(e=c[d])&&(a[d]=!(b[d]=e))}):function(a,c,e){return b[0]=a,f(b,null,e,d),!d.pop()}}),has:c(function(a){return function(c){return 0<b(a,c).length}}),contains:c(function(a){return function(b){return-1<(b.textContent||b.innerText||ja(b)).indexOf(a)}}),lang:c(function(a){return qa.test(a||"")||b.error("unsupported lang: "+a),a=a.replace(ma,na).toLowerCase(),function(b){var c;do if(c=ba?b.lang:b.getAttribute("xml:lang")||
b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===y},focus:function(a){return a===O.activeElement&&(!O.hasFocus||O.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===
b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!E.pseudos.empty(a)},header:function(a){return ua.test(a.nodeName)},input:function(a){return ra.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&
"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:p(function(){return[0]}),last:p(function(a,b){return[b-1]}),eq:p(function(a,b,c){return[0>c?c+b:c]}),even:p(function(a,b){for(var c=0;b>c;c+=2)a.push(c);return a}),odd:p(function(a,b){for(var c=1;b>c;c+=2)a.push(c);return a}),lt:p(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:p(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};E.pseudos.nth=E.pseudos.eq;for(B in{radio:!0,checkbox:!0,
file:!0,password:!0,image:!0})E.pseudos[B]=k(B);for(B in{submit:!0,reset:!0})E.pseudos[B]=l(B);q.prototype=E.filters=E.pseudos;E.setFilters=new q;var fa=b.tokenize=function(a,c){var d,f,e,g,h;if(g=Q[a+" "])return c?0:g.slice(0);g=a;var k=[];for(h=E.preFilter;g;){l&&!(d=ia.exec(g))||(d&&(g=g.slice(d[0].length)||g),k.push(f=[]));var l=!1;(d=ka.exec(g))&&(l=d.shift(),f.push({value:l,type:d[0].replace(U," ")}),g=g.slice(l.length));for(e in E.filter)!(d=Z[e].exec(g))||h[e]&&!(d=h[e](d))||(l=d.shift(),
f.push({value:l,type:e,matches:d}),g=g.slice(l.length));if(!l)break}return c?g.length:g?b.error(a):Q(a,k).slice(0)};return A=b.compile=function(a,b){var c,d=[],f=[],e=ob[a+" "];if(!e){b||(b=fa(a));for(c=b.length;c--;)e=x(b[c]),e[D]?d.push(e):f.push(e);e=ob(a,z(f,d));e.selector=a}return e},F=b.select=function(a,b,c,d){var f,e,g,h,k,l="function"==typeof a&&a,p=!d&&fa(a=l.selector||a);if(c=c||[],1===p.length){if(e=p[0]=p[0].slice(0),2<e.length&&"ID"===(g=e[0]).type&&K.getById&&9===b.nodeType&&ba&&E.relative[e[1].type]){if(b=
(E.find.ID(g.matches[0].replace(ma,na),b)||[])[0],!b)return c;l&&(b=b.parentNode);a=a.slice(e.shift().value.length)}for(f=Z.needsContext.test(a)?0:e.length;f--&&(g=e[f],!E.relative[h=g.type]);)if((k=E.find[h])&&(d=k(g.matches[0].replace(ma,na),ha.test(e[0].type)&&n(b.parentNode)||b))){if(e.splice(f,1),a=d.length&&m(e),!a)return M.apply(c,d),c;break}}return(l||A(a,p))(d,b,!ba,c,ha.test(a)&&n(b.parentNode)||b),c},K.sortStable=D.split("").sort(L).join("")===D,K.detectDuplicates=!!Aa,sa(),K.sortDetached=
e(function(a){return 1&a.compareDocumentPosition(O.createElement("div"))}),e(function(a){return a.innerHTML="<a href='#'></a>","#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){return c?void 0:a.getAttribute(b,"type"===b.toLowerCase()?1:2)}),K.attributes&&e(function(a){return a.innerHTML="<input/>",a.firstChild.setAttribute("value",""),""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){return c||"input"!==a.nodeName.toLowerCase()?void 0:a.defaultValue}),
e(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;return c?void 0:!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null}),b}(m);c.find=oa;c.expr=oa.selectors;c.expr[":"]=c.expr.pseudos;c.unique=oa.uniqueSort;c.text=oa.getText;c.isXMLDoc=oa.isXML;c.contains=oa.contains;var pb=c.expr.match.needsContext,qb=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,
Hb=/^.[^:#\[\.,]*$/;c.filter=function(a,b,d){var f=b[0];return d&&(a=":not("+a+")"),1===b.length&&1===f.nodeType?c.find.matchesSelector(f,a)?[f]:[]:c.find.matches(a,c.grep(b,function(a){return 1===a.nodeType}))};c.fn.extend({find:function(a){var b,d=this.length,f=[],e=this;if("string"!=typeof a)return this.pushStack(c(a).filter(function(){for(b=0;d>b;b++)if(c.contains(e[b],this))return!0}));for(b=0;d>b;b++)c.find(a,e[b],f);return f=this.pushStack(1<d?c.unique(f):f),f.selector=this.selector?this.selector+
" "+a:a,f},filter:function(a){return this.pushStack(F(this,a||[],!1))},not:function(a){return this.pushStack(F(this,a||[],!0))},is:function(a){return!!F(this,"string"==typeof a&&pb.test(a)?c(a):a||[],!1).length}});var Xb=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/;(c.fn.init=function(a,b){var d,f;if(!a)return this;if("string"==typeof a){if(d="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:Xb.exec(a),!d||!d[1]&&b)return!b||b.jquery?(b||Pa).find(a):this.constructor(b).find(a);if(d[1]){if(b=b instanceof
c?b[0]:b,c.merge(this,c.parseHTML(d[1],b&&b.nodeType?b.ownerDocument||b:u,!0)),qb.test(d[1])&&c.isPlainObject(b))for(d in b)c.isFunction(this[d])?this[d](b[d]):this.attr(d,b[d]);return this}return f=u.getElementById(d[2]),f&&f.parentNode&&(this.length=1,this[0]=f),this.context=u,this.selector=a,this}return a.nodeType?(this.context=this[0]=a,this.length=1,this):c.isFunction(a)?"undefined"!=typeof Pa.ready?Pa.ready(a):a(c):(void 0!==a.selector&&(this.selector=a.selector,this.context=a.context),c.makeArray(a,
this))}).prototype=c.fn;var Pa=c(u);var Yb=/^(?:parents|prev(?:Until|All))/,Zb={children:!0,contents:!0,next:!0,prev:!0};c.extend({dir:function(a,b,d){for(var f=[],e=void 0!==d;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(e&&c(a).is(d))break;f.push(a)}return f},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});c.fn.extend({has:function(a){var b=c(a,this),d=b.length;return this.filter(function(){for(var a=0;d>a;a++)if(c.contains(this,b[a]))return!0})},
closest:function(a,b){for(var d,f=0,e=this.length,g=[],h=pb.test(a)||"string"!=typeof a?c(a,b||this.context):0;e>f;f++)for(d=this[f];d&&d!==b;d=d.parentNode)if(11>d.nodeType&&(h?-1<h.index(d):1===d.nodeType&&c.find.matchesSelector(d,a))){g.push(d);break}return this.pushStack(1<g.length?c.unique(g):g)},index:function(a){return a?"string"==typeof a?va.call(c(a),this[0]):va.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(c.unique(c.merge(this.get(),
c(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return y(a,"nextSibling")},prev:function(a){return y(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,
b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return a.contentDocument||c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);return"Until"!==a.slice(-5)&&(f=d),f&&"string"==typeof f&&(e=c.filter(f,e)),1<this.length&&(Zb[a]||c.unique(e),Yb.test(a)&&e.reverse()),this.pushStack(e)}});
var T=/\S+/g,Ua={};c.Callbacks=function(a){a="string"==typeof a?Ua[a]||Q(a):c.extend({},a);var b,d,f,e,g,h,k=[],l=!a.once&&[],p=function(c){b=a.memory&&c;d=!0;h=e||0;e=0;g=k.length;for(f=!0;k&&g>h;h++)if(!1===k[h].apply(c[0],c[1])&&a.stopOnFalse){b=!1;break}f=!1;k&&(l?l.length&&p(l.shift()):b?k=[]:n.disable())},n={add:function(){if(k){var d=k.length;!function v(b){c.each(b,function(b,d){b=c.type(d);"function"===b?a.unique&&n.has(d)||k.push(d):d&&d.length&&"string"!==b&&v(d)})}(arguments);f?g=k.length:
b&&(e=d,p(b))}return this},remove:function(){return k&&c.each(arguments,function(a,b){for(var d;-1<(d=c.inArray(b,k,d));)k.splice(d,1),f&&(g>=d&&g--,h>=d&&h--)}),this},has:function(a){return a?-1<c.inArray(a,k):!(!k||!k.length)},empty:function(){return k=[],g=0,this},disable:function(){return k=l=b=void 0,this},disabled:function(){return!k},lock:function(){return l=void 0,b||n.disable(),this},locked:function(){return!l},fireWith:function(a,b){return!k||d&&!l||(b=b||[],b=[a,b.slice?b.slice():b],f?
l.push(b):p(b)),this},fire:function(){return n.fireWith(this,arguments),this},fired:function(){return!!d}};return n};c.extend({Deferred:function(a){var b=[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",f={state:function(){return d},always:function(){return e.done(arguments).fail(arguments),this},then:function(){var a=arguments;return c.Deferred(function(d){c.each(b,function(b,
g){var h=c.isFunction(a[b])&&a[b];e[g[1]](function(){var a=h&&h.apply(this,arguments);a&&c.isFunction(a.promise)?a.promise().done(d.resolve).fail(d.reject).progress(d.notify):d[g[0]+"With"](this===f?d.promise():this,h?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?c.extend(a,f):f}},e={};return f.pipe=f.then,c.each(b,function(a,c){var g=c[2],h=c[3];f[c[1]]=g.add;h&&g.add(function(){d=h},b[1^a][2].disable,b[2][2].lock);e[c[0]]=function(){return e[c[0]+"With"](this===e?f:this,
arguments),this};e[c[0]+"With"]=g.fireWith}),f.promise(e),a&&a.call(e,e),e},when:function(a){var b=0,d=V.call(arguments),f=d.length,e=1!==f||a&&c.isFunction(a.promise)?f:0,g=1===e?a:c.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?V.call(arguments):d;c===l?g.notifyWith(b,c):--e||g.resolveWith(b,c)}},k;if(1<f){var l=Array(f);var p=Array(f);for(k=Array(f);f>b;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(h(b,k,d)).fail(g.reject).progress(h(b,p,l)):--e}return e||
g.resolveWith(k,d),g.promise()}});var Da;c.fn.ready=function(a){return c.ready.promise().done(a),this};c.extend({isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){(!0===a?--c.readyWait:c.isReady)||(c.isReady=!0,!0!==a&&0<--c.readyWait||(Da.resolveWith(u,[c]),c.fn.triggerHandler&&(c(u).triggerHandler("ready"),c(u).off("ready"))))}});c.ready.promise=function(a){return Da||(Da=c.Deferred(),"complete"===u.readyState?setTimeout(c.ready):(u.addEventListener("DOMContentLoaded",
wa,!1),m.addEventListener("load",wa,!1))),Da.promise(a)};c.ready.promise();var G=c.access=function(a,b,d,f,e,g,h){var k=0,l=a.length,p=null==d;if("object"===c.type(d))for(k in e=!0,d)c.access(a,b,k,d[k],!0,g,h);else if(void 0!==f&&(e=!0,c.isFunction(f)||(h=!0),p&&(h?(b.call(a,f),b=null):(p=b,b=function(a,b,d){return p.call(c(a),d)})),b))for(;l>k;k++)b(a[k],d,h?f:f.call(a[k],k,b(a[k],d)));return e?a:p?b.call(a):l?b(a[0],d):g};c.acceptData=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};
ea.uid=1;ea.accepts=c.acceptData;ea.prototype={key:function(a){if(!ea.accepts(a))return 0;var b={},d=a[this.expando];if(!d){d=ea.uid++;try{b[this.expando]={value:d},Object.defineProperties(a,b)}catch(f){b[this.expando]=d,c.extend(a,b)}}return this.cache[d]||(this.cache[d]={}),d},set:function(a,b,d){var f;a=this.key(a);var e=this.cache[a];if("string"==typeof b)e[b]=d;else if(c.isEmptyObject(e))c.extend(this.cache[a],b);else for(f in b)e[f]=b[f];return e},get:function(a,b){a=this.cache[this.key(a)];
return void 0===b?a:a[b]},access:function(a,b,d){var f;return void 0===b||b&&"string"==typeof b&&void 0===d?(f=this.get(a,b),void 0!==f?f:this.get(a,c.camelCase(b))):(this.set(a,b,d),void 0!==d?d:b)},remove:function(a,b){var d,f,e=this.key(a);a=this.cache[e];if(void 0===b)this.cache[e]={};else for(c.isArray(b)?d=b.concat(b.map(c.camelCase)):(f=c.camelCase(b),b in a?d=[b,f]:(d=f,d=d in a?[d]:d.match(T)||[])),b=d.length;b--;)delete a[d[b]]},hasData:function(a){return!c.isEmptyObject(this.cache[a[this.expando]]||
{})},discard:function(a){a[this.expando]&&delete this.cache[a[this.expando]]}};var w=new ea,B=new ea,Jb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Ib=/([A-Z])/g;c.extend({hasData:function(a){return B.hasData(a)||w.hasData(a)},data:function(a,b,c){return B.access(a,b,c)},removeData:function(a,b){B.remove(a,b)},_data:function(a,b,c){return w.access(a,b,c)},_removeData:function(a,b){w.remove(a,b)}});c.fn.extend({data:function(a,b){var d,f,e,g=this[0],h=g&&g.attributes;if(void 0===a){if(this.length&&(e=B.get(g),
1===g.nodeType&&!w.get(g,"hasDataAttrs"))){for(d=h.length;d--;)h[d]&&(f=h[d].name,0===f.indexOf("data-")&&(f=c.camelCase(f.slice(5)),xa(g,f,e[f])));w.set(g,"hasDataAttrs",!0)}return e}return"object"==typeof a?this.each(function(){B.set(this,a)}):G(this,function(b){var d,f=c.camelCase(a);if(g&&void 0===b){if((d=B.get(g,a),void 0!==d)||(d=B.get(g,f),void 0!==d)||(d=xa(g,f,void 0),void 0!==d))return d}else this.each(function(){var c=B.get(this,f);B.set(this,f,b);-1!==a.indexOf("-")&&void 0!==c&&B.set(this,
a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){B.remove(this,a)})}});c.extend({queue:function(a,b,d){var f;return a?(b=(b||"fx")+"queue",f=w.get(a,b),d&&(!f||c.isArray(d)?f=w.access(a,b,c.makeArray(d)):f.push(d)),f||[]):void 0},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.length,e=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===e&&(e=d.shift(),f--);e&&("fx"===b&&d.unshift("inprogress"),delete g.stop,e.call(a,h,g));
!f&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return w.get(a,d)||w.access(a,d,{empty:c.Callbacks("once memory").add(function(){w.remove(a,[b+"queue",d])})})}});c.fn.extend({queue:function(a,b){var d=2;return"string"!=typeof a&&(b=a,a="fx",d--),arguments.length<d?c.queue(this[0],a):void 0===b?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,
a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,f=1,e=c.Deferred(),g=this,h=this.length,k=function(){--f||e.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(d=w.get(g[h],a+"queueHooks"))&&d.empty&&(f++,d.empty.add(k));return k(),e.promise(b)}});var Ea=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,Y=["Top","Right","Bottom","Left"],Z=function(a,b){return a=b||a,"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)},rb=/^(?:checkbox|radio)$/i;
!function(){var a=u.createDocumentFragment().appendChild(u.createElement("div")),b=u.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);x.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";x.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue}();x.focusinBubbles="onfocusin"in m;var $b=/^key/,ac=/^(?:mouse|pointer|contextmenu)|click/,sb=/^(?:focusinfocus|focusoutblur)$/,
tb=/^([^.]*)(?:\.(.+)|)$/;c.event={global:{},add:function(a,b,d,f,e){var g,h,k,l,p,n,m,u;if(l=w.get(a))for(d.handler&&(g=d,d=g.handler,e=g.selector),d.guid||(d.guid=c.guid++),(k=l.events)||(k=l.events={}),(h=l.handle)||(h=l.handle=function(b){return"undefined"!==typeof c&&c.event.triggered!==b.type?c.event.dispatch.apply(a,arguments):void 0}),b=(b||"").match(T)||[""],l=b.length;l--;){var r=tb.exec(b[l])||[];var v=u=r[1];r=(r[2]||"").split(".").sort();v&&(n=c.event.special[v]||{},v=(e?n.delegateType:
n.bindType)||v,n=c.event.special[v]||{},p=c.extend({type:v,origType:u,data:f,handler:d,guid:d.guid,selector:e,needsContext:e&&c.expr.match.needsContext.test(e),namespace:r.join(".")},g),(m=k[v])||(m=k[v]=[],m.delegateCount=0,n.setup&&!1!==n.setup.call(a,f,r,h)||a.addEventListener&&a.addEventListener(v,h,!1)),n.add&&(n.add.call(a,p),p.handler.guid||(p.handler.guid=d.guid)),e?m.splice(m.delegateCount++,0,p):m.push(p),c.event.global[v]=!0)}},remove:function(a,b,d,f,e){var g,h,k,l,m,n,q,u,r=w.hasData(a)&&
w.get(a);if(r&&(l=r.events)){b=(b||"").match(T)||[""];for(m=b.length;m--;)if(k=tb.exec(b[m])||[],n=u=k[1],q=(k[2]||"").split(".").sort(),n){var v=c.event.special[n]||{};n=(f?v.delegateType:v.bindType)||n;var x=l[n]||[];k=k[2]&&new RegExp("(^|\\.)"+q.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=x.length;g--;){var y=x[g];!e&&u!==y.origType||d&&d.guid!==y.guid||k&&!k.test(y.namespace)||f&&f!==y.selector&&("**"!==f||!y.selector)||(x.splice(g,1),y.selector&&x.delegateCount--,v.remove&&v.remove.call(a,y))}h&&
!x.length&&(v.teardown&&!1!==v.teardown.call(a,q,r.handle)||c.removeEvent(a,n,r.handle),delete l[n])}else for(n in l)c.event.remove(a,n+b[m],d,f,!0);c.isEmptyObject(l)&&(delete r.handle,w.remove(a,"events"))}},trigger:function(a,b,d,f){var e,g,h,k,l,p=[d||u],n=Oa.call(a,"type")?a.type:a;var q=Oa.call(a,"namespace")?a.namespace.split("."):[];if(e=g=d=d||u,3!==d.nodeType&&8!==d.nodeType&&!sb.test(n+c.event.triggered)&&(0<=n.indexOf(".")&&(q=n.split("."),n=q.shift(),q.sort()),h=0>n.indexOf(":")&&"on"+
n,a=a[c.expando]?a:new c.Event(n,"object"==typeof a&&a),a.isTrigger=f?2:3,a.namespace=q.join("."),a.namespace_re=a.namespace?new RegExp("(^|\\.)"+q.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=void 0,a.target||(a.target=d),b=null==b?[a]:c.makeArray(b,[a]),l=c.event.special[n]||{},f||!l.trigger||!1!==l.trigger.apply(d,b))){if(!f&&!l.noBubble&&!c.isWindow(d)){var r=l.delegateType||n;for(sb.test(r+n)||(e=e.parentNode);e;e=e.parentNode)p.push(e),g=e;g===(d.ownerDocument||u)&&p.push(g.defaultView||g.parentWindow||
m)}for(q=0;(e=p[q++])&&!a.isPropagationStopped();)a.type=1<q?r:l.bindType||n,(k=(w.get(e,"events")||{})[a.type]&&w.get(e,"handle"))&&k.apply(e,b),(k=h&&e[h])&&k.apply&&c.acceptData(e)&&(a.result=k.apply(e,b),!1===a.result&&a.preventDefault());return a.type=n,f||a.isDefaultPrevented()||l._default&&!1!==l._default.apply(p.pop(),b)||!c.acceptData(d)||h&&c.isFunction(d[n])&&!c.isWindow(d)&&(g=d[h],g&&(d[h]=null),c.event.triggered=n,d[n](),c.event.triggered=void 0,g&&(d[h]=g)),a.result}},dispatch:function(a){a=
c.event.fix(a);var b,d,f,e,g=V.call(arguments);var h=(w.get(this,"events")||{})[a.type]||[];var k=c.event.special[a.type]||{};if(g[0]=a,a.delegateTarget=this,!k.preDispatch||!1!==k.preDispatch.call(this,a)){var l=c.event.handlers.call(this,a,h);for(h=0;(f=l[h++])&&!a.isPropagationStopped();)for(a.currentTarget=f.elem,b=0;(e=f.handlers[b++])&&!a.isImmediatePropagationStopped();)a.namespace_re&&!a.namespace_re.test(e.namespace)||(a.handleObj=e,a.data=e.data,d=((c.event.special[e.origType]||{}).handle||
e.handler).apply(f.elem,g),void 0===d||!1!==(a.result=d)||(a.preventDefault(),a.stopPropagation()));return k.postDispatch&&k.postDispatch.call(this,a),a.result}},handlers:function(a,b){var d,f=[],e=b.delegateCount,g=a.target;if(e&&g.nodeType&&(!a.button||"click"!==a.type))for(;g!==this;g=g.parentNode||this)if(!0!==g.disabled||"click"!==a.type){var h=[];for(d=0;e>d;d++){var k=b[d];var l=k.selector+" ";void 0===h[l]&&(h[l]=k.needsContext?0<=c(l,this).index(g):c.find(l,this,null,[g]).length);h[l]&&h.push(k)}h.length&&
f.push({elem:g,handlers:h})}return e<b.length&&f.push({elem:this,handlers:b.slice(e)}),f},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){return null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode),a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),
filter:function(a,b){var c,f,e,g=b.button;return null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||u,f=c.documentElement,e=c.body,a.pageX=b.clientX+(f&&f.scrollLeft||e&&e.scrollLeft||0)-(f&&f.clientLeft||e&&e.clientLeft||0),a.pageY=b.clientY+(f&&f.scrollTop||e&&e.scrollTop||0)-(f&&f.clientTop||e&&e.clientTop||0)),a.which||void 0===g||(a.which=1&g?1:2&g?3:4&g?2:0),a}},fix:function(a){if(a[c.expando])return a;var b=a.type;var d=a,f=this.fixHooks[b];f||(this.fixHooks[b]=f=ac.test(b)?this.mouseHooks:
$b.test(b)?this.keyHooks:{});var e=f.props?this.props.concat(f.props):this.props;a=new c.Event(d);for(b=e.length;b--;){var g=e[b];a[g]=d[g]}return a.target||(a.target=u),3===a.target.nodeType&&(a.target=a.target.parentNode),f.filter?f.filter(a,d):a},special:{load:{noBubble:!0},focus:{trigger:function(){return this!==Va()&&this.focus?(this.focus(),!1):void 0},delegateType:"focusin"},blur:{trigger:function(){return this===Va()&&this.blur?(this.blur(),!1):void 0},delegateType:"focusout"},click:{trigger:function(){return"checkbox"===
this.type&&this.click&&c.nodeName(this,"input")?(this.click(),!1):void 0},_default:function(a){return c.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,d,f){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,originalEvent:{}});f?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,
c,!1)};c.Event=function(a,b){return this instanceof c.Event?(a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?M:U):this.type=a,b&&c.extend(this,b),this.timeStamp=a&&a.timeStamp||c.now(),void(this[c.expando]=!0)):new c.Event(a,b)};c.Event.prototype={isDefaultPrevented:U,isPropagationStopped:U,isImmediatePropagationStopped:U,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=M;a&&a.preventDefault&&
a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=M;a&&a.stopPropagation&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=M;a&&a.stopImmediatePropagation&&a.stopImmediatePropagation();this.stopPropagation()}};c.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(a){var d,
e=a.relatedTarget,g=a.handleObj;return(!e||e!==this&&!c.contains(this,e))&&(a.type=g.origType,d=g.handler.apply(this,arguments),a.type=b),d}}});x.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=function(a){c.event.simulate(b,a.target,c.event.fix(a),!0)};c.event.special[b]={setup:function(){var c=this.ownerDocument||this,e=w.access(c,b);e||c.addEventListener(a,d,!0);w.access(c,b,(e||0)+1)},teardown:function(){var c=this.ownerDocument||this,e=w.access(c,b)-1;e?w.access(c,
b,e):(c.removeEventListener(a,d,!0),w.remove(c,b))}}});c.fn.extend({on:function(a,b,d,f,e){var g,h;if("object"==typeof a){"string"!=typeof b&&(d=d||b,b=void 0);for(h in a)this.on(h,b,d,a[h],e);return this}if(null==d&&null==f?(f=b,d=b=void 0):null==f&&("string"==typeof b?(f=d,d=void 0):(f=d,d=b,b=void 0)),!1===f)f=U;else if(!f)return this;return 1===e&&(g=f,f=function(a){return c().off(a),g.apply(this,arguments)},f.guid=g.guid||(g.guid=c.guid++)),this.each(function(){c.event.add(this,a,f,d,b)})},one:function(a,
b,c,f){return this.on(a,b,c,f,1)},off:function(a,b,d){var f,e;if(a&&a.preventDefault&&a.handleObj)return f=a.handleObj,c(a.delegateTarget).off(f.namespace?f.origType+"."+f.namespace:f.origType,f.selector,f.handler),this;if("object"==typeof a){for(e in a)this.off(e,b,a[e]);return this}return(!1===b||"function"==typeof b)&&(d=b,b=void 0),!1===d&&(d=U),this.each(function(){c.event.remove(this,a,d,b)})},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,
b){var d=this[0];return d?c.event.trigger(a,b,d,!0):void 0}});var ub=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,vb=/<([\w:]+)/,bc=/<|&#?\w+;/,cc=/<(?:script|style|link)/i,dc=/checked\s*(?:[^=]|=\s*.checked.)/i,wb=/^$|\/(?:java|ecma)script/i,Mb=/^true\/(.*)/,ec=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,L={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],
td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};L.optgroup=L.option;L.tbody=L.tfoot=L.colgroup=L.caption=L.thead;L.th=L.td;c.extend({clone:function(a,b,d){var f,e=a.cloneNode(!0),g=c.contains(a.ownerDocument,a);if(!(x.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a))){var h=C(e);var k=C(a);var l=0;for(f=k.length;f>l;l++){var m=k[l],n=h[l],q=n.nodeName.toLowerCase();"input"===q&&rb.test(m.type)?n.checked=m.checked:("input"===q||"textarea"===q)&&(n.defaultValue=
m.defaultValue)}}if(b)if(d)for(k=k||C(a),h=h||C(e),l=0,f=k.length;f>l;l++)Xa(k[l],h[l]);else Xa(a,e);return h=C(e,"script"),0<h.length&&Ha(h,!g&&C(a,"script")),e},buildFragment:function(a,b,d,f){for(var e,g,h,k,l=b.createDocumentFragment(),m=[],n=0,q=a.length;q>n;n++)if(e=a[n],e||0===e)if("object"===c.type(e))c.merge(m,e.nodeType?[e]:e);else if(bc.test(e)){g=g||l.appendChild(b.createElement("div"));h=(vb.exec(e)||["",""])[1].toLowerCase();h=L[h]||L._default;g.innerHTML=h[1]+e.replace(ub,"<$1></$2>")+
h[2];for(h=h[0];h--;)g=g.lastChild;c.merge(m,g.childNodes);g=l.firstChild;g.textContent=""}else m.push(b.createTextNode(e));l.textContent="";for(n=0;e=m[n++];)if((!f||-1===c.inArray(e,f))&&(k=c.contains(e.ownerDocument,e),g=C(l.appendChild(e),"script"),k&&Ha(g),d))for(h=0;e=g[h++];)wb.test(e.type||"")&&d.push(e);return l},cleanData:function(a){for(var b,d,f,e,g=c.event.special,h=0;void 0!==(d=a[h]);h++){if(c.acceptData(d)&&(e=d[w.expando],e&&(b=w.cache[e]))){if(b.events)for(f in b.events)g[f]?c.event.remove(d,
f):c.removeEvent(d,f,b.handle);w.cache[e]&&delete w.cache[e]}delete B.cache[d[B.expando]]}}});c.fn.extend({text:function(a){return G(this,function(a){return void 0===a?c.text(this):this.empty().each(function(){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||(this.textContent=a)})},null,a,arguments.length)},append:function(){return this.domManip(arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||Wa(this,a).appendChild(a)})},prepend:function(){return this.domManip(arguments,
function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=Wa(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var d=a?c.filter(a,this):this,f=0;null!=(a=d[f]);f++)b||1!==a.nodeType||c.cleanData(C(a)),a.parentNode&&
(b&&c.contains(a.ownerDocument,a)&&Ha(C(a,"script")),a.parentNode.removeChild(a));return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(c.cleanData(C(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null==a?!1:a,b=null==b?a:b,this.map(function(){return c.clone(this,a,b)})},html:function(a){return G(this,function(a){var b=this[0]||{},f=0,e=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"==typeof a&&!cc.test(a)&&!L[(vb.exec(a)||
["",""])[1].toLowerCase()]){a=a.replace(ub,"<$1></$2>");try{for(;e>f;f++)b=this[f]||{},1===b.nodeType&&(c.cleanData(C(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=arguments[0];return this.domManip(arguments,function(b){a=this.parentNode;c.cleanData(C(this));a&&a.replaceChild(b,this)}),a&&(a.length||a.nodeType)?this:this.remove()},detach:function(a){return this.remove(a,!0)},domManip:function(a,b){a=nb.apply([],a);var d,f,e,
g=0,h=this.length,k=this,l=h-1,m=a[0],n=c.isFunction(m);if(n||1<h&&"string"==typeof m&&!x.checkClone&&dc.test(m))return this.each(function(c){var d=k.eq(c);n&&(a[0]=m.call(this,c,d.html()));d.domManip(a,b)});if(h&&(d=c.buildFragment(a,this[0].ownerDocument,!1,this),f=d.firstChild,1===d.childNodes.length&&(d=f),f)){f=c.map(C(d,"script"),Kb);for(e=f.length;h>g;g++){var q=d;g!==l&&(q=c.clone(q,!0,!0),e&&c.merge(f,C(q,"script")));b.call(this[g],q,g)}if(e)for(d=f[f.length-1].ownerDocument,c.map(f,Lb),
g=0;e>g;g++)q=f[g],wb.test(q.type||"")&&!w.access(q,"globalEval")&&c.contains(d,q)&&(q.src?c._evalUrl&&c._evalUrl(q.src):c.globalEval(q.textContent.replace(ec,"")))}return this}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(a){for(var d=[],e=c(a),g=e.length-1,h=0;g>=h;h++)a=h===g?this:this.clone(!0),c(e[h])[b](a),Na.apply(d,a.get());return this.pushStack(d)}});var ha,Za={},$a=/^margin/,Ja=new RegExp("^("+
Ea+")(?!px)[a-z%]+$","i"),ya=function(a){return a.ownerDocument.defaultView.getComputedStyle(a,null)};!function(){var a,b,d=u.documentElement,f=u.createElement("div"),e=u.createElement("div");if(e.style){var g=function(){e.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:block;margin-top:1%;top:1%;border:1px;padding:1px;width:4px;position:absolute";e.innerHTML="";d.appendChild(f);var c=m.getComputedStyle(e,null);a="1%"!==c.top;b="4px"===c.width;
d.removeChild(f)};e.style.backgroundClip="content-box";e.cloneNode(!0).style.backgroundClip="";x.clearCloneStyle="content-box"===e.style.backgroundClip;f.style.cssText="border:0;width:0;height:0;top:0;left:-9999px;margin-top:1px;position:absolute";f.appendChild(e);m.getComputedStyle&&c.extend(x,{pixelPosition:function(){return g(),a},boxSizingReliable:function(){return null==b&&g(),b},reliableMarginRight:function(){var a,b=e.appendChild(u.createElement("div"));return b.style.cssText=e.style.cssText=
"-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;display:block;margin:0;border:0;padding:0",b.style.marginRight=b.style.width="0",e.style.width="1px",d.appendChild(f),a=!parseFloat(m.getComputedStyle(b,null).marginRight),d.removeChild(f),a}})}}();c.swap=function(a,b,c,f){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,f||[]);for(d in b)a.style[d]=g[d];return c};var fc=/^(none|table(?!-c[ea]).+)/,Nb=new RegExp("^("+Ea+")(.*)$","i"),gc=new RegExp("^([+-])=("+
Ea+")","i"),hc={position:"absolute",visibility:"hidden",display:"block"},xb={letterSpacing:"0",fontWeight:"400"},cb=["Webkit","O","Moz","ms"];c.extend({cssHooks:{opacity:{get:function(a,b){if(b)return a=qa(a,"opacity"),""===a?"1":a}}},cssNumber:{columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,d,f){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var e,g,h,
k=c.camelCase(b),l=a.style;return b=c.cssProps[k]||(c.cssProps[k]=bb(l,k)),h=c.cssHooks[b]||c.cssHooks[k],void 0===d?h&&"get"in h&&void 0!==(e=h.get(a,!1,f))?e:l[b]:(g=typeof d,"string"===g&&(e=gc.exec(d))&&(d=(e[1]+1)*e[2]+parseFloat(c.css(a,b)),g="number"),null!=d&&d===d&&("number"!==g||c.cssNumber[k]||(d+="px"),x.clearCloneStyle||""!==d||0!==b.indexOf("background")||(l[b]="inherit"),h&&"set"in h&&void 0===(d=h.set(a,d,f))||(l[b]=d)),void 0)}},css:function(a,b,d,f){var e,g,h,k=c.camelCase(b);return b=
c.cssProps[k]||(c.cssProps[k]=bb(a.style,k)),h=c.cssHooks[b]||c.cssHooks[k],h&&"get"in h&&(e=h.get(a,!0,d)),void 0===e&&(e=qa(a,b,f)),"normal"===e&&b in xb&&(e=xb[b]),""===d||d?(g=parseFloat(e),!0===d||c.isNumeric(g)?g||0:e):e}});c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,f,e){return f?fc.test(c.css(a,"display"))&&0===a.offsetWidth?c.swap(a,hc,function(){return fb(a,b,e)}):fb(a,b,e):void 0},set:function(a,f,e){var d=e&&ya(a);return db(a,f,e?eb(a,b,e,"border-box"===c.css(a,
"boxSizing",!1,d),d):0)}}});c.cssHooks.marginRight=ab(x.reliableMarginRight,function(a,b){return b?c.swap(a,{display:"inline-block"},qa,[a,"marginRight"]):void 0});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){var d=0,e={};for(c="string"==typeof c?c.split(" "):[c];4>d;d++)e[a+Y[d]+b]=c[d]||c[d-2]||c[0];return e}};$a.test(a)||(c.cssHooks[a+b].set=db)});c.fn.extend({css:function(a,b){return G(this,function(a,b,e){var d,f={},k=0;if(c.isArray(b)){e=ya(a);
for(d=b.length;d>k;k++)f[b[k]]=c.css(a,b[k],!1,e);return f}return void 0!==e?c.style(a,b,e):c.css(a,b)},a,b,1<arguments.length)},show:function(){return gb(this,!0)},hide:function(){return gb(this)},toggle:function(a){return"boolean"==typeof a?a?this.show():this.hide():this.each(function(){Z(this)?c(this).show():c(this).hide()})}});c.Tween=H;H.prototype={constructor:H,init:function(a,b,d,f,e,g){this.elem=a;this.prop=d;this.easing=e||"swing";this.options=b;this.start=this.now=this.cur();this.end=f;
this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=H.propHooks[this.prop];return a&&a.get?a.get(this):H.propHooks._default.get(this)},run:function(a){var b,d=H.propHooks[this.prop];return this.pos=b=this.options.duration?c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),d&&d.set?d.set(this):H.propHooks._default.set(this),this}};H.prototype.init.prototype=
H.prototype;H.propHooks={_default:{get:function(a){var b;return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(b=c.css(a.elem,a.prop,""),b&&"auto"!==b?b:0):a.elem[a.prop]},set:function(a){c.fx.step[a.prop]?c.fx.step[a.prop](a):a.elem.style&&(null!=a.elem.style[c.cssProps[a.prop]]||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};H.propHooks.scrollTop=H.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};
c.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2}};c.fx=H.prototype.init;c.fx.step={};var ia,Fa,ic=/^(?:toggle|show|hide)$/,yb=new RegExp("^(?:([+-])=|)("+Ea+")([a-z%]*)$","i"),jc=/queueHooks$/,ja=[function(a,b,d){var f,e,g,h,k,l,m,n=this,q={},r=a.style,u=a.nodeType&&Z(a),v=w.get(a,"fxshow");d.queue||(h=c._queueHooks(a,"fx"),null==h.unqueued&&(h.unqueued=0,k=h.empty.fire,h.empty.fire=function(){h.unqueued||k()}),h.unqueued++,n.always(function(){n.always(function(){h.unqueued--;
c.queue(a,"fx").length||h.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(d.overflow=[r.overflow,r.overflowX,r.overflowY],l=c.css(a,"display"),m="none"===l?w.get(a,"olddisplay")||Ia(a.nodeName):l,"inline"===m&&"none"===c.css(a,"float")&&(r.display="inline-block"));d.overflow&&(r.overflow="hidden",n.always(function(){r.overflow=d.overflow[0];r.overflowX=d.overflow[1];r.overflowY=d.overflow[2]}));for(f in b)if(e=b[f],ic.exec(e)){if(delete b[f],g=g||"toggle"===e,e===(u?"hide":"show")){if("show"!==
e||!v||void 0===v[f])continue;u=!0}q[f]=v&&v[f]||c.style(a,f)}else l=void 0;if(c.isEmptyObject(q))"inline"===("none"===l?Ia(a.nodeName):l)&&(r.display=l);else for(f in v?"hidden"in v&&(u=v.hidden):v=w.access(a,"fxshow",{}),g&&(v.hidden=!u),u?c(a).show():n.done(function(){c(a).hide()}),n.done(function(){var b;w.remove(a,"fxshow");for(b in q)c.style(a,b,q[b])}),q)b=ib(u?v[f]:0,f,n),f in v||(v[f]=b.start,u&&(b.end=b.start,b.start="width"===f||"height"===f?1:0))}],ra={"*":[function(a,b){var d=this.createTween(a,
b),f=d.cur(),e=(b=yb.exec(b))&&b[3]||(c.cssNumber[a]?"":"px"),g=(c.cssNumber[a]||"px"!==e&&+f)&&yb.exec(c.css(d.elem,a)),h=1,k=20;if(g&&g[3]!==e){e=e||g[3];b=b||[];g=+f||1;do h=h||".5",g/=h,c.style(d.elem,a,g+e);while(h!==(h=d.cur()/f)&&1!==h&&--k)}return b&&(g=d.start=+g||+f||0,d.unit=e,d.end=b[1]?g+(b[1]+1)*b[2]:+b[2]),d}]};c.Animation=c.extend(jb,{tweener:function(a,b){c.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var d,f=0,e=a.length;e>f;f++)d=a[f],ra[d]=ra[d]||[],ra[d].unshift(b)},prefilter:function(a,
b){b?ja.unshift(a):ja.push(a)}});c.speed=function(a,b,d){var f=a&&"object"==typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};return f.duration=c.fx.off?0:"number"==typeof f.duration?f.duration:f.duration in c.fx.speeds?c.fx.speeds[f.duration]:c.fx.speeds._default,(null==f.queue||!0===f.queue)&&(f.queue="fx"),f.old=f.complete,f.complete=function(){c.isFunction(f.old)&&f.old.call(this);f.queue&&c.dequeue(this,f.queue)},f};c.fn.extend({fadeTo:function(a,
b,c,f){return this.filter(Z).css("opacity",0).show().end().animate({opacity:b},a,c,f)},animate:function(a,b,d,f){var e=c.isEmptyObject(a),g=c.speed(b,d,f);b=function(){var b=jb(this,c.extend({},a),g);(e||w.get(this,"finish"))&&b.stop(!0)};return b.finish=b,e||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,d){var f=function(a){var b=a.stop;delete a.stop;b(d)};return"string"!=typeof a&&(d=b,b=a,a=void 0),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&
a+"queueHooks",h=c.timers,k=w.get(this);if(g)k[g]&&k[g].stop&&f(k[g]);else for(g in k)k[g]&&k[g].stop&&jc.test(g)&&f(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(d),b=!1,h.splice(g,1));!b&&d||c.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b=w.get(this),d=b[a+"queue"];var f=b[a+"queueHooks"];var e=c.timers,g=d?d.length:0;b.finish=!0;c.queue(this,a,[]);f&&f.stop&&f.stop.call(this,!0);for(f=e.length;f--;)e[f].elem===
this&&e[f].queue===a&&(e[f].anim.stop(!0),e.splice(f,1));for(f=0;g>f;f++)d[f]&&d[f].finish&&d[f].finish.call(this);delete b.finish})}});c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(a,c,g){return null==a||"boolean"==typeof a?d.apply(this,arguments):this.animate(za(b,!0),a,c,g)}});c.each({slideDown:za("show"),slideUp:za("hide"),slideToggle:za("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,e){return this.animate(b,
a,c,e)}});c.timers=[];c.fx.tick=function(){var a=0,b=c.timers;for(ia=c.now();a<b.length;a++){var d=b[a];d()||b[a]!==d||b.splice(a--,1)}b.length||c.fx.stop();ia=void 0};c.fx.timer=function(a){c.timers.push(a);a()?c.fx.start():c.timers.pop()};c.fx.interval=13;c.fx.start=function(){Fa||(Fa=setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=function(){clearInterval(Fa);Fa=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fn.delay=function(a,b){return a=c.fx?c.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,
function(b,c){var d=setTimeout(b,a);c.stop=function(){clearTimeout(d)}})};(function(){var a=u.createElement("input"),b=u.createElement("select"),c=b.appendChild(u.createElement("option"));a.type="checkbox";x.checkOn=""!==a.value;x.optSelected=c.selected;b.disabled=!0;x.optDisabled=!c.disabled;a=u.createElement("input");a.value="t";a.type="radio";x.radioValue="t"===a.value})();var ua=c.expr.attrHandle;c.fn.extend({attr:function(a,b){return G(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,
a)})}});c.extend({attr:function(a,b,d){var f,e,g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g)return"undefined"===typeof a.getAttribute?c.prop(a,b,d):(1===g&&c.isXMLDoc(a)||(b=b.toLowerCase(),f=c.attrHooks[b]||(c.expr.match.bool.test(b)?kc:void 0)),void 0===d?f&&"get"in f&&null!==(e=f.get(a,b))?e:(e=c.find.attr(a,b),null==e?void 0:e):null!==d?f&&"set"in f&&void 0!==(e=f.set(a,d,b))?e:(a.setAttribute(b,d+""),d):void c.removeAttr(a,b))},removeAttr:function(a,b){var d=0,f=b&&b.match(T);if(f&&1===a.nodeType)for(;b=
f[d++];){var e=c.propFix[b]||b;c.expr.match.bool.test(b)&&(a[e]=!1);a.removeAttribute(b)}},attrHooks:{type:{set:function(a,b){if(!x.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;return a.setAttribute("type",b),d&&(a.value=d),b}}}}});var kc={set:function(a,b,d){return!1===b?c.removeAttr(a,d):a.setAttribute(d,d),d}};c.each(c.expr.match.bool.source.match(/\w+/g),function(a,b){var d=ua[b]||c.find.attr;ua[b]=function(a,b,c){var f,e;return c||(e=ua[b],ua[b]=f,f=null!=d(a,b,c)?b.toLowerCase():
null,ua[b]=e),f}});var lc=/^(?:input|select|textarea|button)$/i;c.fn.extend({prop:function(a,b){return G(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[c.propFix[a]||a]})}});c.extend({propFix:{"for":"htmlFor","class":"className"},prop:function(a,b,d){var f,e,g,h=a.nodeType;if(a&&3!==h&&8!==h&&2!==h)return g=1!==h||!c.isXMLDoc(a),g&&(b=c.propFix[b]||b,e=c.propHooks[b]),void 0!==d?e&&"set"in e&&void 0!==(f=e.set(a,d,b))?f:a[b]=d:e&&"get"in e&&null!==
(f=e.get(a,b))?f:a[b]},propHooks:{tabIndex:{get:function(a){return a.hasAttribute("tabindex")||lc.test(a.nodeName)||a.href?a.tabIndex:-1}}}});x.optSelected||(c.propHooks.selected={get:function(a){a=a.parentNode;return a&&a.parentNode&&a.parentNode.selectedIndex,null}});c.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){c.propFix[this.toLowerCase()]=this});var Qa=/[\t\r\n\f]/g;c.fn.extend({addClass:function(a){var b,
d,f,e;var g="string"==typeof a&&a;var h=0,k=this.length;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});if(g)for(g=(a||"").match(T)||[];k>h;h++)if(b=this[h],d=1===b.nodeType&&(b.className?(" "+b.className+" ").replace(Qa," "):" ")){for(e=0;f=g[e++];)0>d.indexOf(" "+f+" ")&&(d+=f+" ");d=c.trim(d);b.className!==d&&(b.className=d)}return this},removeClass:function(a){var b,d,f,e;var g=0===arguments.length||"string"==typeof a&&a;var h=0,k=this.length;
if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,this.className))});if(g)for(g=(a||"").match(T)||[];k>h;h++)if(b=this[h],d=1===b.nodeType&&(b.className?(" "+b.className+" ").replace(Qa," "):"")){for(e=0;f=g[e++];)for(;0<=d.indexOf(" "+f+" ");)d=d.replace(" "+f+" "," ");d=a?c.trim(d):"";b.className!==d&&(b.className=d)}return this},toggleClass:function(a,b){var d=typeof a;return"boolean"==typeof b&&"string"===d?b?this.addClass(a):this.removeClass(a):this.each(c.isFunction(a)?
function(d){c(this).toggleClass(a.call(this,d,this.className,b),b)}:function(){if("string"===d)for(var b,e=0,g=c(this),h=a.match(T)||[];b=h[e++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else("undefined"===d||"boolean"===d)&&(this.className&&w.set(this,"__className__",this.className),this.className=this.className||!1===a?"":w.get(this,"__className__")||"")})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;c>b;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(Qa," ").indexOf(a))return!0;
return!1}});var mc=/\r/g;c.fn.extend({val:function(a){var b,d,f,e=this[0];if(arguments.length)return f=c.isFunction(a),this.each(function(d){var e;1===this.nodeType&&(e=f?a.call(this,d,c(this).val()):a,null==e?e="":"number"==typeof e?e+="":c.isArray(e)&&(e=c.map(e,function(a){return null==a?"":a+""})),b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,e,"value")||(this.value=e))});if(e)return b=c.valHooks[e.type]||c.valHooks[e.nodeName.toLowerCase()],
b&&"get"in b&&void 0!==(d=b.get(e,"value"))?d:(d=e.value,"string"==typeof d?d.replace(mc,""):null==d?"":d)}});c.extend({valHooks:{option:{get:function(a){var b=c.find.attr(a,"value");return null!=b?b:c.trim(c.text(a))}},select:{get:function(a){for(var b,d=a.options,f=a.selectedIndex,e="select-one"===a.type||0>f,g=e?null:[],h=e?f+1:d.length,k=0>f?h:e?f:0;h>k;k++)if(b=d[k],!(!b.selected&&k!==f||(x.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&c.nodeName(b.parentNode,
"optgroup"))){if(a=c(b).val(),e)return a;g.push(a)}return g},set:function(a,b){for(var d,f=a.options,e=c.makeArray(b),g=f.length;g--;)b=f[g],(b.selected=0<=c.inArray(b.value,e))&&(d=!0);return d||(a.selectedIndex=-1),e}}}});c.each(["radio","checkbox"],function(){c.valHooks[this]={set:function(a,b){return c.isArray(b)?a.checked=0<=c.inArray(c(a).val(),b):void 0}};x.checkOn||(c.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,null,a,c):this.trigger(b)}});c.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,f){return this.on(b,a,c,f)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});var Ra=c.now(),Sa=/\?/;c.parseJSON=function(a){return JSON.parse(a+"")};c.parseXML=
function(a){if(!a||"string"!=typeof a)return null;try{var b=new DOMParser;var d=b.parseFromString(a,"text/xml")}catch(f){d=void 0}return(!d||d.getElementsByTagName("parsererror").length)&&c.error("Invalid XML: "+a),d};var nc=/#.*$/,zb=/([?&])_=[^&]*/,oc=/^(.*?):[ \t]*([^\r\n]*)$/gm,pc=/^(?:GET|HEAD)$/,qc=/^\/\//,Ab=/^([\w.+-]+:)(?:\/\/(?:[^\/?#]*@|)([^\/?#:]*)(?::(\d+)|)|)/,Bb={},Ka={},Cb="*/".concat("*");try{var da=location.href}catch(a){da=u.createElement("a"),da.href="",da=da.href}var pa=Ab.exec(da.toLowerCase())||
[];c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:da,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(pa[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Cb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,
"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?La(La(a,c.ajaxSettings),b):La(c.ajaxSettings,a)},ajaxPrefilter:kb(Bb),ajaxTransport:kb(Ka),ajax:function(a,b){function d(a,b,d,g){var k,m,p,x=b;if(2!==z){z=2;h&&clearTimeout(h);f=void 0;e=g||"";A.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(d){var v=n;for(var B=A,D,P,C,I,M=v.contents,H=v.dataTypes;"*"===H[0];)H.shift(),void 0===D&&(D=v.mimeType||B.getResponseHeader("Content-Type"));
if(D)for(P in M)if(M[P]&&M[P].test(D)){H.unshift(P);break}if(H[0]in d)C=H[0];else{for(P in d){if(!H[0]||v.converters[P+" "+H[0]]){C=P;break}I||(I=P)}C=C||I}v=C?(C!==H[0]&&H.unshift(C),d[C]):void 0}a:{d=n;D=v;P=A;C=g;var G,L,Q;v={};B=d.dataTypes.slice();if(B[1])for(G in d.converters)v[G.toLowerCase()]=d.converters[G];for(I=B.shift();I;)if(d.responseFields[I]&&(P[d.responseFields[I]]=D),!Q&&C&&d.dataFilter&&(D=d.dataFilter(D,d.dataType)),Q=I,I=B.shift())if("*"===I)I=Q;else if("*"!==Q&&Q!==I){if(G=v[Q+
" "+I]||v["* "+I],!G)for(O in v)if(L=O.split(" "),L[1]===I&&(G=v[Q+" "+L[0]]||v["* "+L[0]])){!0===G?G=v[O]:!0!==v[O]&&(I=L[0],B.unshift(L[1]));break}if(!0!==G)if(G&&d["throws"])D=G(D);else try{D=G(D)}catch(Wb){var O={state:"parsererror",error:G?Wb:"No conversion from "+Q+" to "+I};break a}}O={state:"success",data:D}}v=O;g?(n.ifModified&&(p=A.getResponseHeader("Last-Modified"),p&&(c.lastModified[F]=p),p=A.getResponseHeader("etag"),p&&(c.etag[F]=p)),204===a||"HEAD"===n.type?x="nocontent":304===a?x=
"notmodified":(x=v.state,k=v.data,m=v.error,g=!m)):(m=x,(a||!x)&&(x="error",0>a&&(a=0)));A.status=a;A.statusText=(b||x)+"";g?u.resolveWith(q,[k,x,A]):u.rejectWith(q,[A,x,m]);A.statusCode(y);y=void 0;l&&r.trigger(g?"ajaxSuccess":"ajaxError",[A,n,g?k:m]);w.fireWith(q,[A,x]);l&&(r.trigger("ajaxComplete",[A,n]),--c.active||c.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=void 0);b=b||{};var f,e,g,h,k,l,m,n=c.ajaxSetup({},b),q=n.context||n,r=n.context&&(q.nodeType||q.jquery)?c(q):c.event,u=c.Deferred(),
w=c.Callbacks("once memory"),y=n.statusCode||{},x={},B={},z=0,C="canceled",A={readyState:0,getResponseHeader:function(a){var b;if(2===z){if(!g)for(g={};b=oc.exec(e);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return 2===z?e:null},setRequestHeader:function(a,b){var c=a.toLowerCase();return z||(a=B[c]=B[c]||a,x[a]=b),this},overrideMimeType:function(a){return z||(n.mimeType=a),this},statusCode:function(a){var b;if(a)if(2>z)for(b in a)y[b]=
[y[b],a[b]];else A.always(a[A.status]);return this},abort:function(a){a=a||C;return f&&f.abort(a),d(0,a),this}};if(u.promise(A).complete=w.add,A.success=A.done,A.error=A.fail,n.url=((a||n.url||da)+"").replace(nc,"").replace(qc,pa[1]+"//"),n.type=b.method||b.type||n.method||n.type,n.dataTypes=c.trim(n.dataType||"*").toLowerCase().match(T)||[""],null==n.crossDomain&&(k=Ab.exec(n.url.toLowerCase()),n.crossDomain=!(!k||k[1]===pa[1]&&k[2]===pa[2]&&(k[3]||("http:"===k[1]?"80":"443"))===(pa[3]||("http:"===
pa[1]?"80":"443")))),n.data&&n.processData&&"string"!=typeof n.data&&(n.data=c.param(n.data,n.traditional)),lb(Bb,n,b,A),2===z)return A;(l=n.global)&&0===c.active++&&c.event.trigger("ajaxStart");n.type=n.type.toUpperCase();n.hasContent=!pc.test(n.type);var F=n.url;n.hasContent||(n.data&&(F=n.url+=(Sa.test(F)?"&":"?")+n.data,delete n.data),!1===n.cache&&(n.url=zb.test(F)?F.replace(zb,"$1_="+Ra++):F+(Sa.test(F)?"&":"?")+"_="+Ra++));n.ifModified&&(c.lastModified[F]&&A.setRequestHeader("If-Modified-Since",
c.lastModified[F]),c.etag[F]&&A.setRequestHeader("If-None-Match",c.etag[F]));(n.data&&n.hasContent&&!1!==n.contentType||b.contentType)&&A.setRequestHeader("Content-Type",n.contentType);A.setRequestHeader("Accept",n.dataTypes[0]&&n.accepts[n.dataTypes[0]]?n.accepts[n.dataTypes[0]]+("*"!==n.dataTypes[0]?", "+Cb+"; q=0.01":""):n.accepts["*"]);for(m in n.headers)A.setRequestHeader(m,n.headers[m]);if(n.beforeSend&&(!1===n.beforeSend.call(q,A,n)||2===z))return A.abort();C="abort";for(m in{success:1,error:1,
complete:1})A[m](n[m]);if(f=lb(Ka,n,b,A)){A.readyState=1;l&&r.trigger("ajaxSend",[A,n]);n.async&&0<n.timeout&&(h=setTimeout(function(){A.abort("timeout")},n.timeout));try{z=1,f.send(x,d)}catch(P){if(!(2>z))throw P;d(-1,P)}}else d(-1,"No Transport");return A},getJSON:function(a,b,d){return c.get(a,b,d,"json")},getScript:function(a,b){return c.get(a,void 0,b,"script")}});c.each(["get","post"],function(a,b){c[b]=function(a,f,e,g){return c.isFunction(f)&&(g=g||e,e=f,f=void 0),c.ajax({url:a,type:b,dataType:g,
data:f,success:e})}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.on(b,a)}});c._evalUrl=function(a){return c.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,"throws":!0})};c.fn.extend({wrapAll:function(a){var b;return c.isFunction(a)?this.each(function(b){c(this).wrapAll(a.call(this,b))}):(this[0]&&(b=c(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var a=
this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)),this)},wrapInner:function(a){return this.each(c.isFunction(a)?function(b){c(this).wrapInner(a.call(this,b))}:function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()}});c.expr.filters.hidden=
function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)};var rc=/%20/g,Pb=/\[\]$/,Db=/\r?\n/g,sc=/^(?:submit|button|image|reset|file)$/i,tc=/^(?:input|select|textarea|keygen)/i;c.param=function(a,b){var d,f=[],e=function(a,b){b=c.isFunction(b)?b():null==b?"":b;f[f.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(void 0===b&&(b=c.ajaxSettings&&c.ajaxSettings.traditional),c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,
function(){e(this.name,this.value)});else for(d in a)Ma(d,a[d],b,e);return f.join("&").replace(rc,"+")};c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&tc.test(this.nodeName)&&!sc.test(a)&&(this.checked||!rb.test(a))}).map(function(a,b){a=c(this).val();return null==a?null:c.isArray(a)?
c.map(a,function(a){return{name:b.name,value:a.replace(Db,"\r\n")}}):{name:b.name,value:a.replace(Db,"\r\n")}}).get()}});c.ajaxSettings.xhr=function(){try{return new XMLHttpRequest}catch(a){}};var uc=0,Ga={},vc={0:200,1223:204},X=c.ajaxSettings.xhr();m.ActiveXObject&&c(m).on("unload",function(){for(var a in Ga)Ga[a]()});x.cors=!!X&&"withCredentials"in X;x.ajax=X=!!X;c.ajaxTransport(function(a){var b;return x.cors||X&&!a.crossDomain?{send:function(c,f){var d,g=a.xhr(),h=++uc;if(g.open(a.type,a.url,
a.async,a.username,a.password),a.xhrFields)for(d in a.xhrFields)g[d]=a.xhrFields[d];a.mimeType&&g.overrideMimeType&&g.overrideMimeType(a.mimeType);a.crossDomain||c["X-Requested-With"]||(c["X-Requested-With"]="XMLHttpRequest");for(d in c)g.setRequestHeader(d,c[d]);b=function(a){return function(){b&&(delete Ga[h],b=g.onload=g.onerror=null,"abort"===a?g.abort():"error"===a?f(g.status,g.statusText):f(vc[g.status]||g.status,g.statusText,"string"==typeof g.responseText?{text:g.responseText}:void 0,g.getAllResponseHeaders()))}};
g.onload=b();g.onerror=b("error");b=Ga[h]=b("abort");try{g.send(a.hasContent&&a.data||null)}catch(k){if(b)throw k;}},abort:function(){b&&b()}}:void 0});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){return c.globalEval(a),a}}});c.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});c.ajaxTransport("script",
function(a){if(a.crossDomain){var b,d;return{send:function(f,e){b=c("<script>").prop({async:!0,charset:a.scriptCharset,src:a.url}).on("load error",d=function(a){b.remove();d=null;a&&e("error"===a.type?404:200,a.type)});u.head.appendChild(b[0])},abort:function(){d&&d()}}}});var Eb=[],Ta=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Eb.pop()||c.expando+"_"+Ra++;return this[a]=!0,a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var f,e,g,h=!1!==a.jsonp&&(Ta.test(a.url)?
"url":"string"==typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Ta.test(a.data)&&"data");return h||"jsonp"===a.dataTypes[0]?(f=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(Ta,"$1"+f):!1!==a.jsonp&&(a.url+=(Sa.test(a.url)?"&":"?")+a.jsonp+"="+f),a.converters["script json"]=function(){return g||c.error(f+" was not called"),g[0]},a.dataTypes[0]="json",e=m[f],m[f]=function(){g=arguments},d.always(function(){m[f]=
e;a[f]&&(a.jsonpCallback=b.jsonpCallback,Eb.push(f));g&&c.isFunction(e)&&e(g[0]);g=e=void 0}),"script"):void 0});c.parseHTML=function(a,b,d){if(!a||"string"!=typeof a)return null;"boolean"==typeof b&&(d=b,b=!1);b=b||u;var f=qb.exec(a);d=!d&&[];return f?[b.createElement(f[1])]:(f=c.buildFragment([a],b,d),d&&d.length&&c(d).remove(),c.merge([],f.childNodes))};var Fb=c.fn.load;c.fn.load=function(a,b,d){if("string"!=typeof a&&Fb)return Fb.apply(this,arguments);var f,e,g,h=this,k=a.indexOf(" ");return 0<=
k&&(f=c.trim(a.slice(k)),a=a.slice(0,k)),c.isFunction(b)?(d=b,b=void 0):b&&"object"==typeof b&&(e="POST"),0<h.length&&c.ajax({url:a,type:e,dataType:"html",data:b}).done(function(a){g=arguments;h.html(f?c("<div>").append(c.parseHTML(a)).find(f):a)}).complete(d&&function(a,b){h.each(d,g||[a.responseText,b,a])}),this};c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var Gb=m.document.documentElement;c.offset={setOffset:function(a,b,d){var f,e,g,h=c.css(a,
"position"),k=c(a),l={};"static"===h&&(a.style.position="relative");var m=k.offset();var n=c.css(a,"top");var q=c.css(a,"left");("absolute"===h||"fixed"===h)&&-1<(n+q).indexOf("auto")?(f=k.position(),g=f.top,e=f.left):(g=parseFloat(n)||0,e=parseFloat(q)||0);c.isFunction(b)&&(b=b.call(a,d,m));null!=b.top&&(l.top=b.top-m.top+g);null!=b.left&&(l.left=b.left-m.left+e);"using"in b?b.using.call(a,l):k.css(l)}};c.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(b){c.offset.setOffset(this,
a,b)});var b,d,f=this[0],e={top:0,left:0},g=f&&f.ownerDocument;if(g)return b=g.documentElement,c.contains(b,f)?("undefined"!==typeof f.getBoundingClientRect&&(e=f.getBoundingClientRect()),d=mb(g),{top:e.top+d.pageYOffset-b.clientTop,left:e.left+d.pageXOffset-b.clientLeft}):e},position:function(){if(this[0]){var a,b,d=this[0],f={top:0,left:0};return"fixed"===c.css(d,"position")?b=d.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),c.nodeName(a[0],"html")||(f=a.offset()),f.top+=c.css(a[0],
"borderTopWidth",!0),f.left+=c.css(a[0],"borderLeftWidth",!0)),{top:b.top-f.top-c.css(d,"marginTop",!0),left:b.left-f.left-c.css(d,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||Gb;a&&!c.nodeName(a,"html")&&"static"===c.css(a,"position");)a=a.offsetParent;return a||Gb})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d="pageYOffset"===b;c.fn[a]=function(c){return G(this,function(a,c,f){var e=mb(a);return void 0===
f?e?e[b]:a[c]:void(e?e.scrollTo(d?m.pageXOffset:f,d?f:m.pageYOffset):a[c]=f)},a,c,arguments.length,null)}});c.each(["top","left"],function(a,b){c.cssHooks[b]=ab(x.pixelPosition,function(a,f){return f?(f=qa(a,b),Ja.test(f)?c(a).position()[b]+"px":f):void 0})});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,f){c.fn[f]=function(e,f){var g=arguments.length&&(d||"boolean"!=typeof e),k=d||(!0===e||!0===f?"margin":"border");return G(this,
function(b,d,e){var f;return c.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+a],b.body["offset"+a],f["offset"+a],f["client"+a])):void 0===e?c.css(b,d,k):c.style(b,d,e,k)},b,g?e:void 0,g,null)}})});c.fn.size=function(){return this.length};c.fn.andSelf=c.fn.addBack;"function"==typeof define&&define.amd&&define("jquery",[],function(){return c});var wc=m.jQuery,xc=m.$;return c.noConflict=function(a){return m.$===c&&(m.$=xc),
a&&m.jQuery===c&&(m.jQuery=wc),c},"undefined"===typeof z&&(m.jQuery=m.$=c),c});
(function(m,z,r){function F(m){return("/"===m[0]?"https://dascritch.net":"")+m}var y=[];r(function(){z.getElementById("s2").innerHTML="@";z.getElementById("a0").href="mailto:"+r("h2").eq(0).text().trim()+"?subject=J'ai vu votre site professionnel";r.ajax({type:"GET",url:"./data/listing.json",dataType:"json",error:function(){console.error("Unable to load feed")},success:function(m){r("#blog").find('article[id!="plussurleblog"]').remove();var y=r("#plussurleblog"),z;for(z in m)if(m.hasOwnProperty(z)){var M=
m[z];y.before('<article><a class="bloc" href="'+F(M.url)+'"><img alt="" src="'+F(M.img)+'" class="right" /><h3>'+M.title+"</h3><p>"+M.intro+"</p></a></article>")}}});r(z).on("keydown",function(m){y.push(m.keyCode);0<=y.toString().indexOf("38,38,40,40,37,39,37,39,66,65")&&(y=[],z.body.id="konami")});var m=r("#carte");m.on("mouseenter focus","a",function(){m.find("span").css("opacity",.3);m.find("span."+this.className).css("opacity",1)}).on("mouseleave blur","a",function(){m.find("span").css("opacity",
1)})})})(window,document,jQuery);
